### ISSUE TITLE
Criar pagina de listar usuarios

### ISSUE THREAD

**Issue by alessandrofeitoza** [digitalcollege-classes/php-merenda#7]
## O QUE
Precisamos de uma nova para listar usuarios, que fique disponivel quando o usuario clicar na opcao "Usuarios" no menu lateral.

### O que mostrar
Olhar com os olhos o arquivo de `src/Entity/User.php` caso ja existe e preencher as colunas da tabela no HTML utilizando esses atributos

**Obs: ** Nao eh necessario o uso de dados reais vindo do banco de dados, essa task eh apenas para ter uma visao da aplicacao

**Comment by ghost** [comment]
# Snapshot da Tela Listar Usuários
![Image](https://github.com/user-attachments/assets/a7d91590-9055-4041-a83e-14ef8b658de2)
